'use client';

import { Heart, Play, Settings2 } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { notify } from '@/components/NotificationCenter';
import { SynauraAppShell, SynauraPanel, SynauraTopBar } from '@/components/synaura/SynauraShell';
import { SynauraContentCard } from '@/components/ui/SynauraContentCard';
import { SynauraConfirmDialog, SynauraOverlay, SynauraOverlayDescription, SynauraOverlayTitle } from '@/components/ui/SynauraOverlay';
import { SynauraBadge, SynauraButton, SynauraCheckbox, SynauraIconButton, SynauraInput, SynauraSelect, SynauraSlider, SynauraSwitch, SynauraTabs, SynauraTextarea } from '@/components/ui/SynauraPrimitives';
import { SynauraCardSkeleton, SynauraEmptyState, SynauraErrorState, SynauraInlineLoading, SynauraProfileSkeleton, SynauraTrackSkeleton } from '@/components/ui/SynauraStates';

const colors = ['background', 'surface', 'surface-muted', 'elevated-surface', 'accent', 'accent-blue', 'accent-coral', 'accent-gold', 'success', 'warning', 'destructive', 'focus'] as const;

function LabSection({ title, children }: { title: string; children: ReactNode }) {
  return <section className="grid gap-4"><h2 className="text-xl font-black">{title}</h2><SynauraPanel className="p-4 sm:p-6">{children}</SynauraPanel></section>;
}

export default function ComponentLab() {
  const [tab, setTab] = useState<'one' | 'two'>('one');
  const [enabled, setEnabled] = useState(true);
  const [overlay, setOverlay] = useState<'none' | 'modal' | 'sheet' | 'drawer' | 'confirm'>('none');
  return <SynauraAppShell><SynauraTopBar /><main className="mx-auto grid max-w-6xl gap-8 pb-24"><header><SynauraBadge tone="warning">Développement uniquement</SynauraBadge><h1 className="mt-3 text-4xl font-black">Synaura UI Lab</h1><p className="mt-2 text-[var(--syn-text-secondary)]">Contrat visuel et comportemental de la fondation web.</p></header>
    <LabSection title="Tokens"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-6">{colors.map((color) => <div key={color}><div className="h-16 rounded-[var(--syn-radius-md)] border border-[var(--syn-border)]" style={{ background: `var(--syn-${color})` }} /><code className="mt-1 block text-[10px] text-[var(--syn-text-secondary)]">--syn-{color}</code></div>)}</div></LabSection>
    <LabSection title="Typographie"><div className="space-y-3"><h1 className="text-4xl font-black">Titre de page</h1><h2 className="text-2xl font-black">Titre de section</h2><h3 className="text-lg font-black">Titre de carte</h3><p className="max-w-2xl text-sm leading-6 text-[var(--syn-text-secondary)]">Un corps lisible et stable, pensé pour les interfaces musicales denses comme pour les moments calmes.</p><code className="block font-mono text-xs">00:42.185 · 128 BPM</code></div></LabSection>
    <LabSection title="Actions"><div className="flex flex-wrap gap-3"><SynauraButton>Principal</SynauraButton><SynauraButton variant="accent"><Play className="h-4 w-4" />Écouter</SynauraButton><SynauraButton variant="secondary">Secondaire</SynauraButton><SynauraButton variant="ghost">Discret</SynauraButton><SynauraButton variant="danger">Supprimer</SynauraButton><SynauraButton loading>Chargement</SynauraButton><SynauraButton disabled>Désactivé</SynauraButton><SynauraIconButton label="Ajouter aux favoris" variant="secondary"><Heart className="h-4 w-4" /></SynauraIconButton></div></LabSection>
    <LabSection title="Formulaires"><div className="grid gap-4 md:grid-cols-2"><SynauraInput label="Titre" placeholder="Nom du morceau" hint="80 caractères maximum" /><SynauraInput label="Champ invalide" defaultValue="?" error="Choisis un titre explicite." /><SynauraTextarea label="Description" placeholder="Raconte l’histoire du morceau…" /><SynauraSelect label="Visibilité" defaultValue="public"><option value="public">Publique</option><option value="private">Privée</option></SynauraSelect><SynauraCheckbox label="Autoriser les remixes" description="Les créateurs pourront dériver ce morceau." defaultChecked /><div className="flex items-center justify-between"><span className="text-sm font-black">Normalisation audio</span><SynauraSwitch checked={enabled} onCheckedChange={setEnabled} label="Normalisation audio" /></div><SynauraSlider label="Volume" min="0" max="100" defaultValue="70" /></div></LabSection>
    <LabSection title="Navigation et badges"><div className="grid gap-4"><SynauraTabs items={[{ value: 'one', label: 'Pour toi' }, { value: 'two', label: 'Nouveautés' }]} value={tab} onChange={setTab} /><div className="flex flex-wrap gap-2"><SynauraBadge>Neutre</SynauraBadge><SynauraBadge tone="accent">Studio</SynauraBadge><SynauraBadge tone="success">Publié</SynauraBadge><SynauraBadge tone="warning">À vérifier</SynauraBadge><SynauraBadge tone="danger">Erreur</SynauraBadge></div></div></LabSection>
    <LabSection title="Contenus"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4"><SynauraContentCard kind="track" title="Ondes nocturnes" subtitle="Mina A." badge="Nouveau" onPlay={() => notify.music('Lecture', 'Ondes nocturnes')} /><SynauraContentCard kind="playlist" title="Horizons synthétiques" subtitle="24 titres" /><SynauraContentCard kind="creator" title="Keurlila" subtitle="Créateur vérifié" /><SynauraContentCard kind="clip" title="Session minuit" subtitle="0:28" /></div></LabSection>
    <LabSection title="Chargement"><div className="grid gap-6 md:grid-cols-2"><div className="space-y-4"><SynauraTrackSkeleton /><SynauraTrackSkeleton /><SynauraProfileSkeleton /></div><div className="grid grid-cols-2 gap-3"><SynauraCardSkeleton /><SynauraCardSkeleton /></div><SynauraInlineLoading label="Analyse du master…" /></div></LabSection>
    <LabSection title="États"><div className="grid gap-4 md:grid-cols-2"><SynauraEmptyState compact title="Playlist vide" description="Ajoute tes premiers titres." action={{ label: 'Découvrir', href: '/discover' }} /><SynauraErrorState compact description="La section n’a pas pu être chargée." action={{ label: 'Réessayer' }} /></div></LabSection>
    <LabSection title="Feedback et overlays"><div className="flex flex-wrap gap-3"><SynauraButton variant="secondary" onClick={() => notify.success('Enregistré', 'Tes changements sont disponibles.')}>Toast succès</SynauraButton><SynauraButton variant="secondary" onClick={() => notify.error('Échec', 'Le morceau n’a pas pu être publié.')}>Toast erreur</SynauraButton><SynauraButton variant="secondary" onClick={() => setOverlay('modal')}>Modal</SynauraButton><SynauraButton variant="secondary" onClick={() => setOverlay('sheet')}>Sheet</SynauraButton><SynauraButton variant="secondary" onClick={() => setOverlay('drawer')}>Drawer</SynauraButton><SynauraButton variant="danger" onClick={() => setOverlay('confirm')}>Confirmation</SynauraButton></div></LabSection>
    <SynauraOverlay open={overlay === 'modal'} onClose={() => setOverlay('none')}><div className="p-6"><SynauraOverlayTitle>Modifier le morceau</SynauraOverlayTitle><SynauraOverlayDescription className="mt-2">Le focus reste piégé ici et revient au déclencheur à la fermeture.</SynauraOverlayDescription><SynauraInput className="mt-5" label="Titre" autoFocus /><SynauraButton className="mt-5" onClick={() => setOverlay('none')}>Enregistrer</SynauraButton></div></SynauraOverlay>
    <SynauraOverlay open={overlay === 'sheet'} onClose={() => setOverlay('none')} presentation="sheet"><div className="p-6"><SynauraOverlayTitle>File de lecture</SynauraOverlayTitle><SynauraOverlayDescription className="mt-2">Présentation adaptée aux écrans tactiles.</SynauraOverlayDescription></div></SynauraOverlay>
    <SynauraOverlay open={overlay === 'drawer'} onClose={() => setOverlay('none')} presentation="drawer-right"><div className="p-6"><SynauraOverlayTitle>Réglages</SynauraOverlayTitle><Settings2 className="mt-6 h-8 w-8" /></div></SynauraOverlay>
    <SynauraConfirmDialog open={overlay === 'confirm'} onClose={() => setOverlay('none')} onConfirm={() => setOverlay('none')} destructive title="Supprimer le brouillon ?" description="Cette action ne peut pas être annulée." confirmLabel="Supprimer" />
  </main></SynauraAppShell>;
}
