-- Genere depuis code-database-map.csv pour le role temporaire Phase 1B.
-- La variable psql phase1b_role doit contenir un identifiant de role existant.
GRANT USAGE ON SCHEMA public TO :"phase1b_role";
GRANT INSERT ON TABLE public.account_private TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.active_artist_boosts TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.active_track_boosts TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.admin_broadcasts TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.admin_email_campaigns TO :"phase1b_role";
GRANT SELECT ON TABLE public.ai_credit_balances TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.ai_generations TO :"phase1b_role";
GRANT INSERT ON TABLE public.ai_playlist_tracks TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.ai_playlists TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.ai_track_likes TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.ai_tracks TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.boosters TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.challenge_entries TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.city_event_participations TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.city_event_tracks TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.city_event_votes TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.city_event_winners TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.city_events TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.city_user_rewards TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.comment_likes TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.comment_moderation TO :"phase1b_role";
GRANT SELECT ON TABLE public.comment_reactions TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.comments TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.conversation_participants TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.conversation_realtime_events TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.conversation_rooms TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.conversations TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.creator_comment_filters TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.creator_posts TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.editorial_collections TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.faq_items TO :"phase1b_role";
GRANT SELECT ON TABLE public.follow_requests TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.forum_post_likes TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.forum_posts TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.forum_replies TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.friendships TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.message_attachments TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.message_hidden_users TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.message_pins TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.message_reactions TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.message_requests TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.messages TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.meteo_alerts TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.meteo_bulletins TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.meteo_comments TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.meteo_reactions TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.meteo_settings TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.meteo_team_members TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.meteo_views TO :"phase1b_role";
GRANT SELECT ON TABLE public.missions TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.music_challenges TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.music_clips TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.notification_preferences TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.notifications TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.password_resets TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.payments TO :"phase1b_role";
GRANT DELETE ON TABLE public.play_stats TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.playlist_tracks TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.playlists TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.post_comments TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.post_likes TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.profiles TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.push_subscriptions TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.recommendation_impressions TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.referrals TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.star_academy_applications TO :"phase1b_role";
GRANT SELECT ON TABLE public.star_academy_config TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.star_academy_staff_applications TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.subscriptions TO :"phase1b_role";
GRANT INSERT ON TABLE public.support_tickets TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.track_events TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.track_likes TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.track_moment_reactions TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.track_remixes TO :"phase1b_role";
GRANT SELECT ON TABLE public.track_stats TO :"phase1b_role";
GRANT SELECT ON TABLE public.track_stats_rolling_30d TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.track_views TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.track_waveforms TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.tracks TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE public.user_blocks TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.user_booster_daily TO :"phase1b_role";
GRANT INSERT, SELECT ON TABLE public.user_booster_open_history TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.user_booster_pack_claims TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.user_booster_pity TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.user_boosters TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.user_daily_spin TO :"phase1b_role";
GRANT INSERT ON TABLE public.user_daily_spin_history TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.user_follows TO :"phase1b_role";
GRANT INSERT, SELECT, UPDATE ON TABLE public.user_missions TO :"phase1b_role";
GRANT SELECT, UPDATE ON TABLE public.user_quotas TO :"phase1b_role";
GRANT DELETE, INSERT, SELECT ON TABLE public.users TO :"phase1b_role";
GRANT USAGE, SELECT ON SEQUENCE public.conversation_participants_id_seq TO :"phase1b_role";
GRANT USAGE, SELECT ON SEQUENCE public.creator_comment_filters_id_seq TO :"phase1b_role";
GRANT USAGE, SELECT ON SEQUENCE public.notifications_id_seq TO :"phase1b_role";
GRANT USAGE, SELECT ON SEQUENCE public.playlist_tracks_id_seq TO :"phase1b_role";
GRANT USAGE, SELECT ON SEQUENCE public.track_likes_id_seq TO :"phase1b_role";
GRANT USAGE, SELECT ON SEQUENCE public.user_follows_id_seq TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.ai_add_credits(uuid, integer) TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.ai_add_credits(uuid, integer, text, text) TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.ai_debit_credits(uuid, integer) TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.ai_debit_credits(uuid, integer, text, text) TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.get_user_ai_stats(uuid) TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.get_user_quota_remaining(uuid) TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.increment_ai_usage(uuid) TO :"phase1b_role";
GRANT EXECUTE ON FUNCTION public.update_follow_counts(uuid) TO :"phase1b_role";
