// lib/aiStudioPresets.ts
import type { AIStudioPreset } from './aiStudioTypes';

export const aiStudioPresets: AIStudioPreset[] = [
  {
    id: 'viral-tiktok-hook',
    emoji: '📱',
    label: 'Viral TikTok Hook',
    description: 'Hook immédiat, refrain court et mémorisable.',
    defaults: {
      title: 'Hook Viral',
      description: 'Créer une chanson courte et ultra accrocheuse pensée pour TikTok : intro instantanée, hook chanté dès les premières secondes, phrase répétable, énergie lumineuse, drop simple et mémorable, structure couplet très court puis refrain explosif.',
      style: 'modern viral pop, catchy TikTok hook, punchy drums, glossy synth bass, bright vocal chops, instant chorus, short intro, memorable topline, radio-ready mix, energetic and playful',
      tags: ['viral', 'hook', 'tiktok', 'pop'],
      isInstrumental: false,
      weirdness: 32,
      styleInfluence: 86,
      audioWeight: 48,
    },
  },
  {
    id: 'edm-neon-festival',
    emoji: '⚡',
    label: 'EDM Néon Festival',
    description: 'Build massif, drop euphorique, scène principale.',
    defaults: {
      title: 'Néon Festival',
      description: 'Créer un hymne EDM festival premium : intro atmosphérique néon, montée très large, snare roll tendu, voix euphorique simple, drop principal massif, kick solide, sidechain marqué, énergie de mainstage nocturne.',
      style: 'festival EDM anthem, neon mainstage, euphoric female vocal, huge supersaw chords, massive build-up, snare roll, powerful drop, sidechain pumping, clean club master, cinematic atmosphere',
      tags: ['edm', 'festival', 'drop massif', 'néon'],
      isInstrumental: false,
      weirdness: 38,
      styleInfluence: 90,
      audioWeight: 56,
    },
  },
  {
    id: 'rap-drole-absurde',
    emoji: '🎭',
    label: 'Rap drôle absurde',
    description: 'Punchlines absurdes, flow fun, refrain viral.',
    defaults: {
      title: 'Punchline Cosmique',
      description: 'Créer un rap français drôle et absurde avec des images inattendues, punchlines mémorables, adlibs exagérés, énergie de freestyle viral, refrain très simple à reprendre, flow précis et production moderne.',
      style: 'funny absurd French rap, bouncy trap drums, playful 808, quirky synth plucks, confident male rap, exaggerated adlibs, viral chorus, witty punchlines, comedic but well-produced',
      tags: ['rap', 'absurde', 'drôle', 'viral'],
      isInstrumental: false,
      weirdness: 68,
      styleInfluence: 76,
      audioWeight: 44,
    },
  },
  {
    id: 'club-melancolique',
    emoji: '🌃',
    label: 'Club mélancolique',
    description: 'Danse nocturne, émotion triste, groove élégant.',
    defaults: {
      title: 'Minuit sur la piste',
      description: 'Créer un titre club mélancolique : groove dansant mais émotion triste, voix intime, basse ronde, pads nocturnes, refrain qui donne envie de danser en pensant à quelqu’un, production élégante et moderne.',
      style: 'melancholic club pop, late night dance track, deep house groove, warm bassline, intimate vocal, emotional minor chords, glossy pads, subtle arpeggios, elegant modern mix',
      tags: ['club', 'mélancolie', 'deep house', 'night'],
      isInstrumental: false,
      weirdness: 34,
      styleInfluence: 84,
      audioWeight: 50,
    },
  },
  {
    id: 'trailer-epique',
    emoji: '🎬',
    label: 'Trailer épique',
    description: 'Montée cinématique, impact, final héroïque.',
    defaults: {
      title: 'Dernier Signal',
      description: 'Créer une musique de bande-annonce épique : démarrage mystérieux, montée progressive, cordes dramatiques, cuivres héroïques, percussions hybrides énormes, impacts cinématiques, final grandiose.',
      style: 'epic cinematic trailer, hybrid orchestral percussion, heroic brass, dramatic strings, huge impacts, rising tension, cinematic choir, massive final climax, high-budget movie trailer',
      tags: ['trailer', 'épique', 'orchestral', 'cinematic'],
      isInstrumental: true,
      weirdness: 30,
      styleInfluence: 92,
      audioWeight: 58,
    },
  },
  {
    id: 'disney-musical',
    emoji: '🏰',
    label: 'Disney Musical',
    description: 'Comédie musicale magique, refrain grand public.',
    defaults: {
      title: 'Je peux briller',
      description: 'Créer une chanson de comédie musicale familiale et magique : couplet narratif, refrain très chantable, orchestration lumineuse, montée émotionnelle, voix expressive, sentiment d’espoir et d’aventure.',
      style: 'family animated musical song, magical orchestration, expressive lead vocal, bright strings, piano, warm brass, theatrical chorus, hopeful lyrics, uplifting cinematic arrangement',
      tags: ['musical', 'magique', 'famille', 'orchestral'],
      isInstrumental: false,
      weirdness: 24,
      styleInfluence: 88,
      audioWeight: 42,
    },
  },
  {
    id: 'metal-orchestral-chaos',
    emoji: '🔥',
    label: 'Metal orchestral chaos',
    description: 'Riffs lourds, orchestre sombre, énergie boss final.',
    defaults: {
      title: 'Chaos Engine',
      description: 'Créer un morceau metal orchestral chaotique : guitares massives, batterie double pédale, cordes agressives, chœurs sombres, breaks cinématiques, tension de boss final, final explosif.',
      style: 'orchestral metal chaos, heavy distorted guitars, double kick drums, aggressive strings, dark choir, cinematic breaks, boss battle energy, intense hybrid mix, explosive ending',
      tags: ['metal', 'orchestral', 'boss battle', 'chaos'],
      isInstrumental: true,
      weirdness: 62,
      styleInfluence: 86,
      audioWeight: 66,
    },
  },
  {
    id: 'anime-opening',
    emoji: '🌸',
    label: 'Anime Opening',
    description: 'Intro énergique, refrain héroïque, J-rock brillant.',
    defaults: {
      title: 'Run to the Sky',
      description: 'Créer un opening d’anime dynamique : intro immédiate, batterie rapide, guitares J-rock brillantes, synthés lumineux, voix héroïque, pré-refrain qui monte, refrain explosif et émotionnel.',
      style: 'anime opening, energetic J-rock, bright electric guitars, fast drums, heroic vocal, emotional pre-chorus, explosive chorus, uplifting synth layers, high energy Japanese pop rock',
      tags: ['anime', 'opening', 'j-rock', 'héroïque'],
      isInstrumental: false,
      weirdness: 42,
      styleInfluence: 88,
      audioWeight: 52,
    },
  },
  {
    id: 'ai-pop-premium',
    emoji: '💎',
    label: 'AI Pop Premium',
    description: 'Pop futuriste, voix glossy, production radio.',
    defaults: {
      title: 'Synthetic Heart',
      description: 'Créer une pop premium futuriste : topline émotionnelle, voix glossy, drums nets, basse précise, synthés élégants, refrain radio, textures IA subtiles mais humaines, production internationale.',
      style: 'premium futuristic pop, glossy lead vocal, radio-ready chorus, tight drums, polished synth bass, elegant digital textures, emotional topline, modern international pop production',
      tags: ['pop premium', 'futuriste', 'radio', 'glossy'],
      isInstrumental: false,
      weirdness: 36,
      styleInfluence: 90,
      audioWeight: 46,
    },
  },
  {
    id: 'synaura-signature',
    emoji: '✨',
    label: 'Synaura Signature',
    description: 'Son Synaura : émotion, néon, drop élégant.',
    defaults: {
      title: 'Synaura Signal',
      description: 'Créer un titre signature Synaura : émotion immédiate, atmosphère néon violette, voix intime puis refrain large, arpèges brillants, basse ronde, drop élégant, sentiment de découverte et de communauté.',
      style: 'Synaura signature sound, emotional neon electronic pop, violet atmosphere, intimate vocal, wide anthemic chorus, shimmering arpeggios, warm bass, elegant drop, futuristic but human',
      tags: ['synaura', 'néon', 'émotion', 'signature'],
      isInstrumental: false,
      weirdness: 46,
      styleInfluence: 92,
      audioWeight: 50,
    },
  },
];

